---
title: "R Notebook"
output: html_notebook
---

#Heatmap
```{r}
# Calculate the rowsum values
rowmeans <- apply(merged_gsea[, 1:6], 1, mean)

# Order the rows based on rowsum values in descending order
ordered_indices <- order(rowmeans, decreasing = TRUE)
ordered_gsea <- merged_gsea[ordered_indices, ]

ordered_gsea <- ordered_gsea %>%  dplyr::select(`451Lu`, SKMEL5, SKMEL28, `1205Lu`, WM793, SKMEL24)

ha <- rowAnnotation(
  foo = anno_mark(
    at = c(100:109),
    labels = c(
      "KEGG_DNA_REPLICATION",
      "KEGG_SPLICEOSOME",
      "REACTOME_DNA_STRAND_ELONGATION",
      "REACTOME_MRNA_SPLICING",
      "REACTOME_ACTIVATION_OF_THE_PRE_REPLICATIVE_COMPLEX",
      "REACTOME_HDR_THROUGH_HOMOLOGOUS_RECOMBINATION_HRR",
      "REACTOME_S_PHASE",
      "REACTOME_PROCESSING_OF_CAPPED_INTRON_CONTAINING_PRE_MRNA",
      "REACTOME_SYNTHESIS_OF_DNA",
      "REACTOME_MITOTIC_SPINDLE_CHECKPOINT"
    ),
    labels_gp = gpar(col = "black", fontsize = 7)  # Adjust the fontsize here
  )
)

row_means_ann <- as.vector(rowMeans(ordered_gsea[, 1:6]))
AVG = HeatmapAnnotation(Avg = anno_barplot(row_means_ann), which = "row")


mitf = HeatmapAnnotation(MITF = sample(letters[1:2], 6, replace = TRUE))

# Create the heatmap
heatmap_gsea_KEGG <- Heatmap(
  ordered_gsea[, 1:6],
  name = "NES",
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_row_names = TRUE,
  show_column_names = TRUE,
  column_names_rot = 45,
  #top_annotation = mitf,
  left_annotation = AVG,
  #right_annotation = ha,
  #rect_gp = gpar(col = "black", lwd = 0.01),
  border_gp = gpar(col = "black"),
  column_names_gp = grid::gpar(fontsize = 8),
  row_names_gp = grid::gpar(fontsize = 8),
  col = colorRamp2(c(-4, 0, 4), colors = c("dodgerblue3", "white", "red"))
)

# Draw the heatmap
draw(heatmap_gsea_KEGG)

```


#volcano - but honestly will probably rather do the violin plots. Also would need to do different colors here - whatever we decide for PD1 and PD1+corin
```{r}
plot <- ggplot(RCOR1_lost_only, aes(x = DMSO.Corin, y = p.value)) +
  geom_point(aes(color = (ifelse(DMSO.Corin < 0 & p.value > 0, "Lost", "Gained"))), size = 1.25) +
  scale_color_manual(values = c("Lost" = "#D2042D", "Gained" = "#b2b2b2"),
                     guide_legend(title = "Interaction")) +
  ylim(0,9)+
  xlim(-4,4)+
  theme_bw() +
  labs(title = "RCOR1 Interactions", y = "-Log2(p-value)", x = "Log2FC(Corin/DMSO)") +
  geom_label_repel(data = subset(RCOR1_lost_only,Gene.name %in% merge$Gene.name & DMSO.Corin <0),
                   aes(label = Gene.name),
                   max.overlaps = Inf, size = 3, nudge_x = -1, nudge_y = 1, segment.size =0.3, force = 2) +

  theme(plot.title = element_text(hjust = 0.5, face = "bold"), legend.position = "bottom")

# Print the plot
print(plot)
```

