---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ngscmdr)
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
```
#Import in DEG files
```{r}
DEG_451 <- read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/filtered/DEG_451_significant.csv")
DEG_1205 <- read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/filtered/DEG_1205_significant.csv")
DEG_SKMEL5 <- read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/filtered/DEG_SKMEL5_significant.csv")
DEG_SKMEL28 <- read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/filtered/DEG_SKMEL28_significant.csv")
DEG_SKMEL24 <- read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/filtered/DEG_SKMEL24_significant.csv")
DEG_WM793 <- read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/filtered/DEG_WM793_significant.csv")
```

#Rename columns within DEG files
```{r}
DEG_451$`451Lu` <- DEG_451$log2FoldChange
keep <- c("451Lu", "Gene.name")
DEG_451 <- DEG_451[,keep]

DEG_1205$`1205Lu` <- DEG_1205$log2FoldChange
keep <- c("1205Lu", "Gene.name")
DEG_1205 <- DEG_1205[,keep]

DEG_SKMEL5$`SKMEL5` <- DEG_SKMEL5$log2FoldChange
keep <- c("SKMEL5", "Gene.name")
DEG_SKMEL5 <- DEG_SKMEL5[,keep]

DEG_SKMEL24$`SKMEL24` <- DEG_SKMEL24$log2FoldChange
keep <- c("SKMEL24", "Gene.name")
DEG_SKMEL24 <- DEG_SKMEL24[,keep]

DEG_SKMEL28$`SKMEL28` <- DEG_SKMEL28$log2FoldChange
keep <- c("SKMEL28", "Gene.name")
DEG_SKMEL28 <- DEG_SKMEL28[,keep]

DEG_WM793$`WM793` <- DEG_WM793$log2FoldChange
keep <- c("WM793", "Gene.name")
DEG_WM793 <- DEG_WM793[,keep]
```

#Merge all DEG's adn write output of all DEG's
```{r}
# Create a list of the tables
DEG_list <- list(DEG_451, DEG_1205, DEG_SKMEL5, DEG_SKMEL28, DEG_SKMEL24, DEG_WM793)

# Merge all tables based on 'Gene.name'
merged_DEG <- Reduce(function(x, y) merge(x, y, by = "Gene.name", all = TRUE), DEG_list)

merged_DEG <- na.omit(merged_DEG)

# Identify duplicate rows based on the 'Gene.name' column
duplicated_rows <- duplicated(merged_DEG$Gene.name) | duplicated(merged_DEG$Gene.name, fromLast = TRUE)

# Remove duplicate rows
unique_dataframe <- merged_DEG[!duplicated_rows, ]

rownames(unique_dataframe) <- unique_dataframe$Gene.name
unique_dataframe <- unique_dataframe[,-1]

write.csv(unique_dataframe, file = "DEG_overlap.csv")
```


#make GSEA NES plot
#import in GSEA result files computed locally
```{r}
neg_451Lu <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/451Lu/splicing_451.GseaPreranked/gsea_report_for_na_neg_1667958245012.tsv")
pos_451Lu <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/451Lu/splicing_451.GseaPreranked/gsea_report_for_na_pos_1667958245012.tsv")

neg_1205Lu <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/1205Lu/splicing_1205.GseaPreranked/gsea_report_for_na_neg_1667960231015.tsv")
pos_1205Lu <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/1205Lu/splicing_1205.GseaPreranked/gsea_report_for_na_pos_1667960231015.tsv")

neg_SKMEL5 <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/SKMEL5/splicing_SKMEL5.GseaPreranked/gsea_report_for_na_neg_1667952772221.tsv")
pos_SKMEL5 <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/SKMEL5/splicing_SKMEL5.GseaPreranked/gsea_report_for_na_pos_1667952772221.tsv")

neg_SKMEL24 <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/SKMEL24/splicing_SKMEL24.GseaPreranked/gsea_report_for_na_neg_1667954868891.tsv")
pos_SKMEL24 <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/SKMEL24/splicing_SKMEL24.GseaPreranked/gsea_report_for_na_pos_1667954868891.tsv")

neg_SKMEL28 <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/SKMEL28/SKMEL28.GseaPreranked/gsea_report_for_na_neg_1707765745744.tsv")
pos_SKMEL28 <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/SKMEL28/SKMEL28.GseaPreranked/gsea_report_for_na_pos_1707765745744.tsv")

neg_WM793 <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/WM793/splicing_WM793.GseaPreranked/gsea_report_for_na_neg_1667948429311.tsv")
pos_WM793 <- read.delim("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/GSEA/GSEA results/WM793/splicing_WM793.GseaPreranked/gsea_report_for_na_pos_1667948429311.tsv")
```

```{r}
gsea_451Lu <- rbind(neg_451Lu,pos_451Lu)
gsea_1205Lu <- rbind(neg_1205Lu,pos_1205Lu)
gsea_WM793 <- rbind(neg_WM793,pos_WM793)
gsea_SKMEL5 <- rbind(neg_SKMEL5,pos_SKMEL5)
gsea_SKMEL24 <- rbind(neg_SKMEL24,pos_SKMEL24)
gsea_SKMEL28 <- rbind(neg_SKMEL28,pos_SKMEL28)
```

```{r}
gsea_451Lu <- gsea_451Lu %>% filter(NOM.p.val<0.05) %>% rename("451Lu" = NES) %>% dplyr::select("NAME", "451Lu")
gsea_1205Lu <- gsea_1205Lu %>% filter(NOM.p.val<0.05) %>% rename("1205Lu" = NES) %>%  dplyr::select("NAME", "1205Lu")
gsea_WM793 <- gsea_WM793 %>% filter(NOM.p.val<0.05) %>% rename("WM793" = NES) %>%  dplyr::select("NAME", "WM793")
gsea_SKMEL24 <- gsea_SKMEL24 %>% filter(NOM.p.val<0.05) %>% rename("SKMEL24" = NES) %>%  dplyr::select("NAME", "SKMEL24")
gsea_SKMEL28 <- gsea_SKMEL28 %>% filter(NOM.p.val<0.05) %>% rename("SKMEL28" = NES) %>%  dplyr::select("NAME", "SKMEL28")
gsea_SKMEL5 <- gsea_SKMEL5 %>% filter(NOM.p.val<0.05) %>% rename("SKMEL5" = NES) %>%  dplyr::select("NAME", "SKMEL5")
```

```{r}
# Create a list of data frames
data_frames <- list(
  gsea_451Lu, gsea_1205Lu, gsea_WM793, 
  gsea_SKMEL24, gsea_SKMEL28, gsea_SKMEL5
)

# Merge data frames by NAME
merged_gsea <- Reduce(function(x, y) merge(x, y, by = "NAME", all = FALSE), data_frames)

# Focus on Hallmark and KEGG pathways
merged_gsea <- merged_gsea[grepl("^KEGG|^HALLMARK", merged_gsea$NAME), ]

# Make rownames
rownames(merged_gsea) <- merged_gsea$NAME
merged_gsea <- merged_gsea[,-1]

# Convert all columns to numeric except the row names
merged_gsea[] <- apply(merged_gsea, 2, as.numeric)

# Remove NA
merged_gsea <- na.omit(merged_gsea)

```


#plot significant pathways
```{r}
# Calculate the rowsum values
rowmeans <- apply(merged_gsea[, 1:6], 1, mean)

# Order the rows based on rowsum values in descending order
ordered_indices <- order(rowmeans, decreasing = TRUE)
ordered_gsea <- merged_gsea[ordered_indices, ]

ordered_gsea <- ordered_gsea %>%  dplyr::select(`451Lu`, SKMEL5, SKMEL28, `1205Lu`, WM793, SKMEL24)

ha <- rowAnnotation(
  foo = anno_mark(
    at = c(100:109),
    labels = c(
      "KEGG_DNA_REPLICATION",
      "KEGG_SPLICEOSOME",
      "REACTOME_DNA_STRAND_ELONGATION",
      "REACTOME_MRNA_SPLICING",
      "REACTOME_ACTIVATION_OF_THE_PRE_REPLICATIVE_COMPLEX",
      "REACTOME_HDR_THROUGH_HOMOLOGOUS_RECOMBINATION_HRR",
      "REACTOME_S_PHASE",
      "REACTOME_PROCESSING_OF_CAPPED_INTRON_CONTAINING_PRE_MRNA",
      "REACTOME_SYNTHESIS_OF_DNA",
      "REACTOME_MITOTIC_SPINDLE_CHECKPOINT"
    ),
    labels_gp = gpar(col = "black", fontsize = 7)  # Adjust the fontsize here
  )
)

row_means_ann <- as.vector(rowMeans(ordered_gsea[, 1:6]))
AVG = HeatmapAnnotation(Avg = anno_barplot(row_means_ann), which = "row")


mitf = HeatmapAnnotation(MITF = sample(letters[1:2], 6, replace = TRUE))

# Create the heatmap
heatmap_gsea_KEGG <- Heatmap(
  ordered_gsea[, 1:6],
  name = "NES",
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  show_row_names = TRUE,
  show_column_names = TRUE,
  column_names_rot = 45,
  #top_annotation = mitf,
  left_annotation = AVG,
  #right_annotation = ha,
  #rect_gp = gpar(col = "black", lwd = 0.01),
  border_gp = gpar(col = "black"),
  column_names_gp = grid::gpar(fontsize = 8),
  row_names_gp = grid::gpar(fontsize = 8),
  col = colorRamp2(c(-4, 0, 4), colors = c("dodgerblue3", "white", "red"))
)

# Draw the heatmap
draw(heatmap_gsea_KEGG)

```
```{r}
pdf(file="heatmap_gsea_KEGG.pdf", width = 5, height = 3)
heatmap_gsea_KEGG
dev.off()
```


#import in KEGG spliceosome gene set
```{r}
KEGG_splice <- read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/DEG/plots/KEGG_splice.csv")
```

```{r}
DEG_withgenes <- unique_dataframe
DEG_withgenes$Gene.name <- rownames(DEG_withgenes)
KEGG_splice_all <- inner_join(KEGG_splice, DEG_withgenes, by = "Gene.name")

rownames(KEGG_splice_all) <- KEGG_splice_all[,1]
KEGG_splice_all <- KEGG_splice_all[,-1]
```


#Plot DEG spliceosome genes as a heatmap
```{r}

# Calculate the rowsum values
rowmeans_KEGG <- rowMeans(KEGG_splice_all[, 1:6])

# Order the rows based on rowsum values in descending order
ordered_indices <- order(rowmeans_KEGG, decreasing = TRUE)
ordered_KEGG <- KEGG_splice_all[ordered_indices, ]

ordered_KEGG <- ordered_KEGG %>% dplyr::select(`451Lu`, SKMEL5, SKMEL28, `1205Lu`, WM793, SKMEL24)


# Define color palette
myColor2 <- colorRampPalette(c("dodgerblue3", 'white'))
paletteLength <- 100  # Define the number of colors in the palette

# Create the heatmap
heatmap <- Heatmap(
  ordered_KEGG,
  name = "Log2FC",
  cluster_columns = TRUE,
  cluster_rows = TRUE,
  column_title = NA,
  show_row_names = TRUE,
  show_column_names = TRUE,
  col = myColor2(paletteLength),
  #fontsize_row = 10,  # Adjust fontsize for row names
  #fontsize_col = 10,  # Adjust fontsize for column names
  column_names_rot = 45,
  border_gp = gpar(col = "black"),
  #main = "DE Splicing Factors",
  row_dend_side = "left",
  column_dend_side = "top",
  #dend_width = unit(5, "mm"),  # Adjust dendrogram width
  row_names_gp = gpar(fontsize = 9),  # Adjust fontsize for row names
  column_names_gp = gpar(fontsize = 10),  # Adjust fontsize for column names
  heatmap_legend_param = list(at = c(-3,-2,-1, 0))  # Adjust legend breaks
)

# Draw the heatmap
draw(heatmap)
```
```{r}
pdf(file="DE_splice_heatmap.pdf", width = 4, height = 6)
heatmap
dev.off()
```


