---
title: "Survival-Associated Corin-induced Events in TCGA-SKCM"
output: html_notebook
---

#using OncoSplicing
```{r}
library(dplyr)
library(ggplot2)

#import in spladder data
SplAdder_Survival <- read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/survival_splice/melanoma/SplAdder_Survival.csv")

#filter events to only include pvalue < 0.05
SplAdder_Survival <- SplAdder_Survival %>% filter(Cancer_Type == "SKCM", Pvalue_HR < 0.05, Splice_Type == "ES", CI_Type == "overall_survival")

#import in commone corin-induced splicing events
common_splice <- read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/rmats/processed_rmats/overlap/Common_Events.csv")

#overlap common splicing events with spladder-identified events to find corin-induced survival associated splicing events
spladder_common <- inner_join(common_splice, SplAdder_Survival, by = "Gene_Symbol")

```

```{r}
#download events and cross reference exon numbers (coordinates won't align because oncosplice uses hg19 and our splicing data uses hg38)
write.csv(spladder_common, file = "spladder_common.csv")
```


```{r}
spladder_common_exons <-  read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/survival_splice/melanoma/spladder_common.csv")
```

```{r}
spladder_common_exons_correct <-  read.csv("/Users/rjfisher/Library/Mobile Documents/com~apple~CloudDocs/BUSM/Alani Lab/DATA/CoREST Splicing/survival_splice/melanoma/spladder_common_correct.csv")
```

```{r}
#Plot SASE

# Select relevant columns
hr_data <- spladder_common_exons_correct[, c("Gene_Symbol", "Hazard_Ratio", "Pvalue_HR", "IncLevelDifference")]

# Filter out NA p-values
hr_data <- hr_data[!is.na(hr_data$Pvalue_HR), ]

# Reorder rows by Hazard Ratio
hr_data <- hr_data[order(hr_data$Hazard_Ratio, decreasing = TRUE), ]

# Create a dotplot
HR_plot <- ggplot(hr_data, aes(x = Hazard_Ratio, y = reorder(Gene_Symbol, Hazard_Ratio), size = -log10(Pvalue_HR), color = factor(ifelse(Hazard_Ratio > 1, "HR>1", "HR<1")))) +
  geom_point() +
  geom_vline(xintercept = 1, linetype = "dashed", color = "black") +
  scale_color_manual(values = c("HR>1" = "red", "HR<1" = "blue"), labels = c("Inclusion", "Exclusion")) +
  labs(x = "Hazard Ratio", y = "Gene Symbol", size = "-log10(P-value)", color = "Corin-Induced:") +
  theme_bw()
HR_plot

```
```{r}
ggsave(HR_plot, width = 4.75,
  height = 3, filename = "HR_plot.pdf")
```


#GO Analysis of Spladder SASE's
```{r}
gontology_SplAdder_Survival <- enrichGO(SplAdder_Survival$Gene_Symbol, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", ont = "all", pvalueCutoff = 0.05, pAdjustMethod = "BH", qvalueCutoff = 0.05, minGSSize = 10, maxGSSize = 500, readable = FALSE)
```

#just SE events
```{r}
gontology_SplAdder_Survival_dotplot<-dotplot(gontology_SplAdder_Survival, split="ONTOLOGY", title = "GO: Survival-Associated Splicing Events ", label_format=75) + facet_grid(ONTOLOGY~., scale="free")+ scale_fill_gradient(low = "dodgerblue3", high = "white") +
  theme(plot.title = element_text(hjust = 0.5,face="bold"))
gontology_SplAdder_Survival_dotplot
```

```{r}
ggsave(gontology_SE_breast_dotplot, width = 8,
  height = 6, filename = "gontology_SE_breast_dotplot.pdf")
```